name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  project_url: "https://github.com/${{github.repository}}"
  # only the paths since there are multiple modules in one release
  latest_manifest_url: "https://github.com/${{github.repository}}/releases/latest/download/"
  release_download_url: "https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Version From Tag
        id: get_version
        run: |
          TAG=${{ github.event.release.tag_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: build
        run: |
          yarn install
          yarn build

      - name: Create zip and rename/enrich module.json files for each language module
        run: |
          for LANG_PATH in dist/*/ ; do
            LANG=${LANG_PATH:5:2}
            ZIP_FILE_NAME="wiki-${LANG}-rqg.zip"
            MODULE_FILE_NAME="${LANG}-module.json"
            MODULE_FOLDER="wiki-${LANG}-rqg"
            DIST_MODULE_FILE_PATH="${LANG_PATH%/}-module.json"

            mkdir "${MODULE_FOLDER}"
            cp -r "${LANG_PATH}"* "${MODULE_FOLDER}"
            mv "${LANG_PATH}"module.json "${DIST_MODULE_FILE_PATH}"
            sed -i "s|#{URL}#|${{ env.project_url }}|" "${DIST_MODULE_FILE_PATH}"
            sed -i "s|#{VERSION}#|${VERSION}|" "${DIST_MODULE_FILE_PATH}"
            sed -i "s|#{MANIFEST}#|${{ env.latest_manifest_url }}${MODULE_FILE_NAME}|" "${DIST_MODULE_FILE_PATH}"
            sed -i "s|#{DOWNLOAD}#|${{ env.release_download_url }}${ZIP_FILE_NAME}|" "${DIST_MODULE_FILE_PATH}"
            zip -r "${ZIP_FILE_NAME}" "${MODULE_FOLDER}"
          done

      #      - name: Display structure of downloaded files
      #        run: ls -R

      # Update the GitHub release with the manifest and module archive files.
      - name: Update Release With Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: ${{ github.event.release.unpublished }}
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./dist/*module.json, ./*.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
